rockset/rockset-go-client

- rockclient.go
> add organization and workspace

- CHANGELOG.md
- doc.go
- example_add_document_test.go
- example_error_handling_test.go
- go.sum
- rockclient.go
- test/rockset_go_test.go
improvements based on customer feedback
> improve documentation and error messaging

- CHANGELOG.md
- lib/go/api_queries.go
- lib/go/model_collection_stats.go
- lib/go/model_organization.go
- lib/go/model_query_error.go
- lib/go/model_query_response.go
- lib/go/model_validate_query_response.go
- add support for query response validation
- fix old changelog version
> add support for query response validation

- example_s3_test.go
- integrations.go
- integrations_test.go
- version.go
also changes the Create*Integration() methods to return the wrapped data
> Get integration

- aliases.go
- api_keys.go
- collections.go
- documents.go
- integrations.go
- integrations_test.go
- ip_allowlist.go
- organizations.go
- users.go
- virtual_instances.go
- workspaces.go
use GetData to avoid nil pointer
> normalize response handling

- integrations.go
yet another forgotten convenience method
> add ListIntegrations() convenience method

- integrations.go
- option/query_lambda.go
- query_lambdas.go
- query_lambdas_test.go
and fix the `CreateKinesisIntegration()` method
> add missing query lambda methods

- rockset.go
- rockset_test.go
adds a ping method which can be used to test network connectivity
> add ping method

- api_keys.go
- option/api_keys.go
- option/role.go
- roles.go
- roles_test.go
adds convenience methods for RBAC
> add support for rbac

- api_keys.go
- api_keys_test.go
- option/api_keys.go
- workspaces_test.go
also add support to suspend & activate api keys
> add support to reveal API keys

- option/format.go
- users.go
- users_test.go
small change to test coveralls
> option to auto-detect format

- .circleci/config.yml
- option/query.go
- queries.go
- queries_test.go
- wait.go
add support for async queries and increase test coverage for queries
> add support for async queries

- option/actions.go
- option/actions_test.go
- option/role.go
- roles_test.go
add new RBAC actions which are missing
> add new rbac actions

- documents_test.go
add test suite for documents: add, patch & delete
> document test suite

- aliases_test.go
- api_keys_test.go
- collections_cc_kc_test.go
- collections_cc_test.go
- collections_kafka_test.go
- documents_test.go
- integration_azure_test.go
- integrations_test.go
- queries_test.go
- query_lambdas_test.go
- rockset_test.go
- roles_test.go
- users_test.go
- views_test.go
turn individual tests into test suites and use per suite workspace
> clean up tests

- aliases_test.go
- api_keys_test.go
- collections_cc_kc_test.go
- collections_cc_test.go
- collections_kafka_test.go
- collections_test.go
- dataset/datasets.go
- dataset/datasets_test.go
- documents_test.go
- error_test.go
- ha_test.go
- integration_azure_test.go
- integrations_test.go
- organizations_test.go
- queries_test.go
- query_lambdas_test.go
- rockset.go
- rockset_test.go
- roles_test.go
- users_test.go
- views_test.go
- virtual_instances_test.go
- workspaces_test.go
use the custom agent for go integratinon tests
> support setting a custom user agent for the client

- retry.go
add jitter to exponential backoff w/default of .05, fix incorrect exponential multiplier in Retry function.
> [SRE-2384] 

- retry.go
- retry_test.go
- rockset.go
support providing a custom error check function for retries
> add support for a custom error check for retries

- writer.go
- writer_test.go
helper to write documents to Rockset
> helper to write documents to rockset

- option/virtual_instance.go
- virtual_instances_test.go
> add option to enable/disable remount on resume

- paginate/query.go
- paginate/query_test.go
add convenience method to get the query result as a channel
> add method to get paginated query results

- .circleci/config.yml
- documents.go
- writer/writer.go
- writer/writer_test.go
updated the test case to cover the bug
> fix a flush timing bug in the writer

- option/collection.go
> add compression type to WithCollectionRequest
