documents.go, documents_test.go, go.mod, go.sum
`PatchDocuments()` doesn't work when you want to patch a top level column, as the value is a `map[string]interface{}`. This changes makes it so you can e.g. replace a value in the `Bar` column for "document id" using
```
[]rockset.PatchDocument{
{
ID: "document id",
Patches: []rockset.PatchOperation{
{
Op:    "replace",
Path:  "/Bar",
Value: true,
},
},
},
}
```
=> replace patch document

ha.go, ha_test.go
This call wrapper allows you to supply a number of `RockClient`s and it will
run the same query on all API client, but return the first query that it gets back,
or an array of errors.
```
api1, _ := rockset.NewClient()
api2, _ := rockset.NewClient()
ha := rockset.NewHA(api1, api2)
res, errs := ha.Query(ctx, "SELECT * FROM commons._events LIMIT 10")
if errs != nil {
for _, err := range errs {
log.Println(err)
}
os.Exit(1)
}
log.Println(res)
```
=> wrapper to make two parallel queries and return the first result

.arcconfig, .golangci.yaml, api_keys.go, collections.go, collections_test.go, example_s3_test.go, go.sum, ha.go, ha_test.go, rockset.go, rockset_test.go, views.go
only two lint errors remain, but one is a false positive, and one needs go1.18 and generics
=> make the code lint clean

documents.go, rockset.go, rockset_test.go
The rs2 cluster is decomissioned, so the client should not use it as a default any longer.
This also changes the client to require an explicit cluster to be provided using an
environment variable or option to the `NewClient()` call.
=> R.I.P. rs2

retry.go, wait.go, workspaces_test.go
workspace creation isn't immediate, so we need to be able to wait until it available
=> add wait for workspace method

collections.go, collections_kafka_test.go, example_s3_test.go, integrations.go, option/collection.go, option/format.go, option/integration.go, rockset_test.go, wait.go
Both the kafka integration and collection have gotten new options. This change adds support for them
and revamps the create collection so that the collection options will be usable in conjunction and 
create a collection from multiple integrations, e.g. S3 and Kafka.
Added a test suite that creates a Confluent Cloud integration, and then a collection from that integration.
```
=== RUN   TestSuiteKafkaCollection
2022-08-30T15:08:45-07:00 TRC api call curation d=909.176542ms
2022-08-30T15:08:45-07:00 DBG total duration d=909.963792ms
=== RUN   TestSuiteKafkaCollection/TestCreateJSONCollection
2022-08-30T15:08:45-07:00 TRC api call curation d=471.724083ms
2022-08-30T15:08:45-07:00 DBG total duration d=471.87675ms
2022-08-30T15:08:46-07:00 TRC api call curation d=184.037083ms …
```
=> update kafka integration & collection support

.circleci/config.yml, collections.go, go.mod
Update to go 1.19 so we can use the new documentation format, and add back `CreateS3Collection()` that was accidentally removed in the previous commit.
=> upgrade to go 1.19 so we can use the enhanced documentation format

aliases_test.go, api_keys_test.go, collections_cc_kc_test.go, collections_cc_test.go, collections_kafka_test.go, collections_test.go, documents_test.go, error_test.go, example_s3_test.go, integration_azure_test.go, integrations_test.go, kafka_test.go, queries_test.go, query_lambdas_test.go, rockset_test.go, roles.go, roles_test.go, users_test.go, views_test.go, virtual_instances_test.go, wait.go
- changes the use of static names so that multiple tests can run in parallel
- replaces logging in the test with `t.Logf()`
- refactor azure tests to match the other tests
- fixes a race condition in `WaitUntilCollectionDocuments()` as it is used in the kafka test
=> refactor test

wait.go, wait_test.go
terraform provider needs to be able to wait for an alias to be gone so
it can clean up  the workspace
=> new wait method and moar tests

retry.go, rockset_test.go, workspaces_test.go
minor fixes
- remove api.use1a1.rockset.com from testing
- log when the calls retry sn operation
- increase test coverage
=> minor fixes

aliases.go, api_keys.go, collections.go, documents.go, error.go, integrations.go, organizations.go, queries.go, query_lambdas.go, retry.go, retry_test.go, roles.go, users.go, views.go, virtual_instances.go, wait_test.go, workspaces.go
This includes a `StatusCode` field in the error, so we can use a proper way to check if the error should be retried. All convenience methods are returning this now, so the `DefaultRetryableErrorCheck()` should work for all calls.
=> proper checks for rereyable errors

example_s3_test.go, option/collection.go
field transformations and clustering key have been deprecated in favor of ingest transformations
=> deprecate options in favor of ingest transform

.circleci/config.yml, option/query.go, option/query_lambda.go, option/virtual_instance.go, queries.go, rockset_test.go, virtual_instances.go, virtual_instances_test.go, wait.go, workspaces_test.go
Add support for using virtual instances
```
go test -timeout 20m -v -run TestVirtualInstanceIntegration
=== RUN   TestVirtualInstanceIntegration
virtual_instances_test.go:103: This test can take more than 10 minutes to run, so make sure to use `go test -timeout 15m`
=== RUN   TestVirtualInstanceIntegration/TestVirtualInstance
virtual_instances_test.go:119: vi c71a7179-1868-454d-93cb-ac811d4dc25e is created
virtual_instances_test.go:123: vi c71a7179-1868-454d-93cb-ac811d4dc25e is active
virtual_instances_test.go:128: workspace go_pme_vi_KExlKM is created
virtual_instances_test.go:132: workspace go_pme_vi_KExlKM is available
virtual_instances_test.go:137: collection go_pme_vi_KExlKM.go_pme_vi_KExlKM is created
virtual_instances_test.go:141: collection has documents …
```
=> multi-vi support

generate.sh
The docker run is performed as root, so files that get created in the volume become undeletable by the user who invoked it. 
This change makes docker run the container with the same uid & gid as the user who invoked it.
=> generate files as current user

example_query_test.go, option/query.go, option/query_lambda.go, virtual_instances_test.go
As titled, we are removing the "generate warnings" feature
=> [ORC-2439] Remove GenerateWarnings option from Go client

wait/virtual_instance.go, wait/virtual_instance_test.go
also support waiting for collection mounts to be active or gone
=> add method to wait until a vi is gone

.golangci.yaml, .pre-commit-config.yaml, aliases_test.go, collections.go, collections_kafka_test.go, errors/rockset.go, errors/rockset_test.go, ha/ha.go, internal/test/string.go, kafka_test.go, option/actions_test.go, organizations_test.go, queries_test.go, retry/exponential.go, retry/exponential_test.go, rockset.go, rockset_test.go, roles_test.go, virtual_instances.go, virtual_instances_test.go, wait/alias_test.go, wait/collections_test.go, wait/query_lambda.go, wait/query_lambda_test.go, wait/query_test.go, wait/virtual_instance.go, wait/virtual_instance_test.go, wait/wait.go, wait/wait_test.go, writer/writer.go
changes no functionality, passes all tests
=> clean up lint and add it to the pre-commit hook

option/query.go, queries.go, queries_test.go
make it easier and more intuitive to execute a query on a VI
added integration test to exercise the code
=> add option.WithVirtualInstance

aliases_test.go, option/alias_test.go, option/api_keys_test.go, option/collection_test.go, option/csv_test.go, option/format_test.go, query_lambdas_test.go, views_test.go, wait/query_lambda.go, wait/wait.go
=> improve test coverage

writer/writer.go, writer/writer_test.go
the `structs.Map()` conversion doesn't honor json tags on the struct,
so we need a way to allow them to be used
=> allow custom conversion function for the writer

aliases_test.go, testdata/cassettes/TestAliasIntegrationSuite.cassette.gz, testdata/cassettes/TestAliases_CRUD.cassette.gz, testdata/cassettes/TestAliases_getAlias.cassette.gz, testdata/cassettes/TestAliases_listAliases.cassette.gz, testdata/cassettes/TestAliases_listAliasesForWorkspace.cassette.gz
`suite.Suite` prevents us from running tests in parallel
=> stop using suite.Suite
